FROM php:8.2-apache

# Установка зависимостей
RUN apt-get update && apt-get install -y \
    libsqlite3-dev \
    zip unzip \
    git \
    && docker-php-ext-install pdo pdo_sqlite

# Копируем проект
COPY . /var/www/html/

# Рабочая директория
WORKDIR /var/www/html/

# Устанавливаем права
RUN chown -R www-data:www-data /var/www/html \
    && a2enmod rewrite

# Устанавливаем Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer